---
- hosts: sonar
  tasks:
  - name: Create Sonar User
    user:
      name: sonar
      create_home: true
      shell: /bin/bash
      comment: "Sonarqube Management Account"
      expires: -1
      password: Gunners23
  
  - name: Deploy Local User SSH Key
    authorized_key:
      user: sonar
      state: present
      manage_dir: true
      key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
  
  - name: Setup Sudo Access for Sonar User
    copy:
      dest: /etc/sudoers.d/sonar
      content: 'sonar ALL=(ALL) NOPASSWD: ALL' 
      validate: /usr/sbin/visudo -cf %s
  
  - name: Enable Password Authentication
    lineinfile:
       dest=/etc/sshd/sshd_config
       regexp='^PasswordAuthentication'
       line="PasswordAuthentication yes"
       state=present
       backup=yes
     notify:
       - restart ssh
  
  - name: Install list of packages
    apt: 
      name: '{{item}}' 
      state: present
    with_items:
      - wget
      - unzip  

  - name: install JDK 11
    apt:
      name: openjdk-11-jdk
      state: present
  
  - name: Change into opt directory
    shell:
      chdir: /home/sonar/opt/
      cmd: mkdir sonarqube

  - name: Download and Unzip Sonarqube then copy into /opt/sonarqube 
    unarchive:
      src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.1.0.47736.zip
      dest: /home/sonar/opt/sonarqube/
      remote_src: yes

  - name: Change ownership for sonarquebe
    file:
      path: /home/sonar/opt/sonarqube/
      owner: sonar
      group: sonar
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes

  - name: Start Sonarqube
    shell: /home/sonar/opt/sonarqube/sonarqube-9.1.0.47736/bin/linux-x86-64/sonar.sh start

  - name: Sonarqube Status
    shell: /home/sonar/opt/sonarqube/sonarqube-9.1.0.47736/bin/linux-x86-64/sonar.sh status
  
  handlers:
  - name: restart ssh
    service:
      name: sshd
      state: restarted
